import { NextResponse, type NextRequest } from "next/server";

const qualityProfiles: Record<string, { label: string; size: string }> = {
  "1080p": { label: "Full HD", size: "2.4 GB" },
  "720p": { label: "HD", size: "1.2 GB" },
  "480p": { label: "Mobile", size: "650 MB" },
};

const trimSlash = (value: string) => value.replace(/\/$/, "");

const sourceFor = (mediaType: string) => {
  if (mediaType === "tv") {
    return (
      process.env.SERIES_DOWNLOAD_BASE_URL ||
      process.env.SHOW_DOWNLOAD_BASE_URL ||
      process.env.NEXT_PUBLIC_SERIES_DOWNLOAD_BASE_URL ||
      process.env.NEXT_PUBLIC_SHOW_DOWNLOAD_BASE_URL ||
      process.env.NEXT_PUBLIC_DOWNLOAD_BASE_URL ||
      process.env.VITE_DOWNLOAD_BASE_URL
    );
  }

  return (
    process.env.MOVIE_DOWNLOAD_BASE_URL ||
    process.env.NEXT_PUBLIC_MOVIE_DOWNLOAD_BASE_URL ||
    process.env.NEXT_PUBLIC_DOWNLOAD_BASE_URL ||
    process.env.VITE_DOWNLOAD_BASE_URL
  );
};

const interpolateSource = ({
  source,
  mediaType,
  id,
  quality,
  season,
}: {
  source: string;
  mediaType: string;
  id: string;
  quality: string;
  season: string | null;
}) => {
  const safeMediaType = mediaType === "tv" ? "tv" : "movie";
  const hasTemplate = /\{(mediaType|type|id|tmdbId|quality|season)\}/.test(source);
  const replacements: Record<string, string> = {
    "{mediaType}": safeMediaType,
    "{type}": safeMediaType,
    "{id}": id,
    "{tmdbId}": id,
    "{quality}": quality,
    "{season}": season || "",
  };

  if (hasTemplate) {
    const url = Object.entries(replacements).reduce(
      (current, [token, value]) => current.replaceAll(token, encodeURIComponent(value)),
      source
    );
    return new URL(url);
  }

  const url = new URL(`${trimSlash(source)}/${safeMediaType}/${id}`);
  url.searchParams.set("quality", quality);
  if (season) url.searchParams.set("season", season);
  return url;
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ mediaType: string; id: string }> }
) {
  const { mediaType, id } = await params;
  const searchParams = request.nextUrl.searchParams;
  const quality = searchParams.get("quality") || "720p";
  const season = searchParams.get("season");
  const profile = qualityProfiles[quality] || qualityProfiles["720p"];
  const safeMediaType = mediaType === "tv" ? "series" : "movie";
  const configuredSource = sourceFor(mediaType);

  if (configuredSource) {
    const sourceUrl = interpolateSource({
      source: configuredSource,
      mediaType,
      id,
      quality,
      season,
    });
    return NextResponse.redirect(sourceUrl);
  }

  const fileName = `jokaflix-${safeMediaType}-${id}${season ? `-season-${season}` : ""}-${quality}.txt`;

  const body = [
    "JokaFlix download test file",
    "",
    `Type: ${safeMediaType}`,
    `TMDB ID: ${id}`,
    season ? `Season: ${season}` : null,
    `Quality: ${quality} (${profile.label})`,
    `Displayed size: ${profile.size}`,
    "",
    "This is a legal placeholder download generated by the Next.js app.",
    "Replace this route with a licensed file source or authorized storage provider when ready.",
  ]
    .filter(Boolean)
    .join("\n");

  return new NextResponse(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${fileName}"`,
      "Cache-Control": "no-store",
    },
  });
}
